import type { AccuracyFixture } from './types';

/**
 * Multi-location accuracy fixtures. No network calls are made in tests — every expected value
 * below is stored locally. See each fixture's `sourceType`/`sourceNote` for provenance:
 * Colombo is independently externally verified; the other five are engine self-consistency
 * fixtures (regression/determinism guards only — see `types.ts` for what that does and does not
 * prove).
 */
export const ACCURACY_FIXTURES: AccuracyFixture[] = [
  {
    name: 'Colombo',
    date: '2024-01-15',
    time: '06:27', // sunrise instant, matching the externally-verified reference below
    timezone: 'Asia/Colombo',
    latitude: 6.9271,
    longitude: 79.8612,
    sourceType: 'external-verified',
    sourceNote:
      'drikpanchang.com, Colombo (geoname-id=1248991), 2024-01-15 — same reference already ' +
      'locked in by chart-engine.accuracy.spec.ts: ayanāṃśa 24.199607, nakṣatra Shatabhisha, ' +
      'Moon sign Kumbha, Sun sign Makara, sunrise 06:27 AM, sunset 06:13 PM.',
    toleranceNote:
      'Ayanāṃśa tolerance ±0.01° (engine 24.1929° vs published 24.1996°, within the ±0.007° gap ' +
      'already documented as acceptable in the existing accuracy report). Sunrise/sunset ' +
      'tolerance ±2 minutes (published times are rounded to the minute). Ascendant is NOT part ' +
      'of the external reference (no published birth-time-dependent ascendant exists for this ' +
      'date) — it is an engine self-consistency value only, computed at the sunrise instant.',
    expected: {
      ayanamsaDeg: 24.1996,
      ayanamsaToleranceDeg: 0.01,
      sunSiderealSign: 'Makara',
      moonSiderealSign: 'Kumbha',
      moonNakshatra: 'Shatabhisha',
      ascendantSign: 'Dhanu', // self-consistency only — see toleranceNote
      sunriseLocal: '06:27',
      sunsetLocal: '18:13',
      sunriseSunsetToleranceMinutes: 2,
      rahuKalaSlot1To8: 2,
    },
    // Sun is ~0.16° from the Dhanu/Makara cusp at this instant (Makara Saṅkrānti falls
    // ~Jan 14–15 most years) — both the engine and the external reference agree on Makara, but
    // the margin is thin enough that a small ephemeris/ayanāṃśa difference could flip it.
    boundarySensitiveFields: ['sunSiderealSign'],
  },
  {
    name: 'Chennai',
    date: '2024-06-15',
    time: '12:00',
    timezone: 'Asia/Kolkata',
    latitude: 13.0827,
    longitude: 80.2707,
    sourceType: 'engine-self-consistency',
    sourceNote:
      'Generated by running JyotishaChartEngine.generate() once on 2024-06-15 and storing the ' +
      'result. Not independently verified against an external panchāṅga — this is a ' +
      'determinism/regression guard only.',
    toleranceNote: 'Ayanāṃśa tolerance ±0.001° (exact engine determinism check, not external tolerance).',
    expected: {
      ayanamsaDeg: 24.198704,
      ayanamsaToleranceDeg: 0.001,
      sunSiderealSign: 'Mithuna',
      moonSiderealSign: 'Kanya',
      moonNakshatra: 'Hasta',
      ascendantSign: 'Simha',
      rahuKalaSlot1To8: 3,
    },
    // Sun is ~0.46° from the Mithuna/Vrishabha cusp (Mithuna Saṅkrānti falls ~June 14–15 most
    // years) — same seasonal-boundary pattern as Colombo above, just a different cusp.
    boundarySensitiveFields: ['sunSiderealSign'],
  },
  {
    name: 'Delhi',
    date: '2024-06-15',
    time: '12:00',
    timezone: 'Asia/Kolkata',
    latitude: 28.6139,
    longitude: 77.209,
    sourceType: 'engine-self-consistency',
    sourceNote:
      'Generated by running JyotishaChartEngine.generate() once on 2024-06-15 and storing the ' +
      'result. Not independently verified against an external panchāṅga — this is a ' +
      'determinism/regression guard only.',
    toleranceNote: 'Ayanāṃśa tolerance ±0.001° (exact engine determinism check, not external tolerance).',
    expected: {
      ayanamsaDeg: 24.198704,
      ayanamsaToleranceDeg: 0.001,
      sunSiderealSign: 'Mithuna',
      moonSiderealSign: 'Kanya',
      moonNakshatra: 'Hasta',
      ascendantSign: 'Simha',
      rahuKalaSlot1To8: 3,
    },
    boundarySensitiveFields: ['sunSiderealSign'],
  },
  {
    name: 'London',
    date: '2024-06-15',
    time: '12:00',
    timezone: 'Europe/London',
    latitude: 51.5074,
    longitude: -0.1278,
    sourceType: 'engine-self-consistency',
    sourceNote:
      'Generated by running JyotishaChartEngine.generate() once on 2024-06-15 and storing the ' +
      'result. Not independently verified against an external panchāṅga — this is a ' +
      'determinism/regression guard only.',
    toleranceNote: 'Ayanāṃśa tolerance ±0.001° (exact engine determinism check, not external tolerance).',
    expected: {
      ayanamsaDeg: 24.198711,
      ayanamsaToleranceDeg: 0.001,
      sunSiderealSign: 'Mithuna',
      moonSiderealSign: 'Kanya',
      moonNakshatra: 'Hasta',
      ascendantSign: 'Simha',
      rahuKalaSlot1To8: 3,
    },
    boundarySensitiveFields: ['sunSiderealSign'],
  },
  {
    name: 'NewYork',
    date: '2024-06-15',
    time: '12:00',
    timezone: 'America/New_York',
    latitude: 40.7128,
    longitude: -74.006,
    sourceType: 'engine-self-consistency',
    sourceNote:
      'Generated by running JyotishaChartEngine.generate() once on 2024-06-15 and storing the ' +
      'result. Not independently verified against an external panchāṅga — this is a ' +
      'determinism/regression guard only.',
    toleranceNote: 'Ayanāṃśa tolerance ±0.001° (exact engine determinism check, not external tolerance).',
    expected: {
      ayanamsaDeg: 24.198719,
      ayanamsaToleranceDeg: 0.001,
      sunSiderealSign: 'Mithuna',
      moonSiderealSign: 'Kanya',
      moonNakshatra: 'Hasta',
      ascendantSign: 'Simha',
      rahuKalaSlot1To8: 3,
    },
    boundarySensitiveFields: ['sunSiderealSign'],
  },
  {
    name: 'Sydney',
    date: '2024-06-15',
    time: '12:00',
    timezone: 'Australia/Sydney',
    latitude: -33.8688,
    longitude: 151.2093,
    sourceType: 'engine-self-consistency',
    sourceNote:
      'Generated by running JyotishaChartEngine.generate() once on 2024-06-15 and storing the ' +
      'result. Not independently verified against an external panchāṅga — this is a ' +
      'determinism/regression guard only.',
    toleranceNote:
      'Ayanāṃśa tolerance ±0.001°. Moon nakṣatra is exceptionally boundary-sensitive for this ' +
      'fixture (~0.12° from the Hasta/Chitra cusp at this exact instant) — treat the ' +
      'moonNakshatra value as fragile to any future engine change, not a strong regression guard.',
    expected: {
      ayanamsaDeg: 24.198697,
      ayanamsaToleranceDeg: 0.001,
      sunSiderealSign: 'Mithuna',
      moonSiderealSign: 'Kanya',
      moonNakshatra: 'Hasta',
      ascendantSign: 'Simha',
      rahuKalaSlot1To8: 3,
    },
    boundarySensitiveFields: ['sunSiderealSign', 'moonNakshatra'],
  },
];
