/**
 * - `"external-verified"`: expected values were sourced from an independent published pañcāṅga
 *   (see each fixture's `sourceNote`) — currently only Colombo 2024-01-15, already locked in by
 *   `chart-engine.accuracy.spec.ts`.
 * - `"engine-self-consistency"`: expected values were generated by running this same engine once
 *   and storing the result. These are determinism/regression guards, NOT independent third-party
 *   verification — they prove "the engine still agrees with itself," not "the engine is correct."
 *   Treat any sign/nakṣatra/ascendant claim from a self-consistency fixture as unverified until
 *   cross-checked against an external source.
 */
export type AccuracyFixtureSourceType = 'external-verified' | 'engine-self-consistency';

export type AccuracyFixtureExpected = {
  ayanamsaDeg: number;
  /** Allowed absolute difference (degrees) between engine output and `ayanamsaDeg`. */
  ayanamsaToleranceDeg: number;
  sunSiderealSign: string;
  moonSiderealSign: string;
  moonNakshatra: string;
  /** Whole-sign ascendant at `time` local — only meaningful given a specific birth time. */
  ascendantSign?: string;
  /** Local civil time, "HH:mm", ±`sunriseSunsetToleranceMinutes`. */
  sunriseLocal?: string;
  sunsetLocal?: string;
  sunriseSunsetToleranceMinutes?: number;
  /** Rāhu kāla 1–8 slot for this weekday (classical-rule, not itself an ephemeris fact). */
  rahuKalaSlot1To8?: number;
};

export type AccuracyFixture = {
  name: string;
  /** Civil date, `YYYY-MM-DD`, local to `timezone`. */
  date: string;
  /** Local civil time, `HH:mm`, used for the ascendant/full-chart fields. */
  time: string;
  timezone: string;
  latitude: number;
  longitude: number;
  sourceType: AccuracyFixtureSourceType;
  sourceNote: string;
  toleranceNote: string;
  expected: AccuracyFixtureExpected;
  /**
   * Field names (matching keys of `expected`) that are near a sign/nakṣatra boundary at this
   * exact instant — for these, tests must not assert strict equality without acknowledging the
   * boundary (see each fixture's test for the actual degrees-from-boundary value).
   */
  boundarySensitiveFields: (keyof AccuracyFixtureExpected)[];
};
